### ISSUE TITLE
Problem Connecting to Server

### ISSUE THREAD

**Issue by soueeks** [Freebi85/Explorico_light#1]
![Server Issue](https://user-images.githubusercontent.com/74749060/99749399-94382a00-2b32-11eb-8965-aa98ef0f3c41.jpg)
 
Anyone know what would cause this? Using Hamachi.

**Comment by Freebi85** [comment]
Join our Discord server in #support-explorico cahnnel if it’s still a thing so we can find out together 😉

Cheers 🍻
